### ISSUE TITLE
Request for CHANGELOG or Release Notes

### ISSUE THREAD

**Issue by dustinsgoodman** [adriencaccia/serverless-analyze-bundle-plugin#5]
Hey @adriencaccia,

First off, I LOVE this plugin. I'm working on an upgrade to a template I maintain to shift to esbuild from webpack and this package is a big reason for my transition. That being said, I unfortunately started by upgrading to Serverless v3 and using v1.0.5 which didn't quite work as intended. I see you've already corrected and fixed the exact issue I saw in v1.0.6 so thank you for that. However, I almost didn't notice the fix due to a lack of CHANGELOG or Release Notes. Could you include this with future releases of the package?

Libraries such as RxJS use tools like https://github.com/commitizen/cz-conventional-changelog that help auto-generate based on your commit/PR history. I think this would really help with adoption. I can probably help set this up if it's something you're interested in.

Best,
Dustin

**Comment by adriencaccia** [comment]
Hey @dustinsgoodman !

Thanks for the really kind message, I am really glad that you like and use the plugin :wink: 

When I have the time, I will look into adding automatic changelog. But if you want to get a crack at it feel free !
I would gladly accept your contributions

**Comment by dustinsgoodman** [comment]
Sounds great! I'm going to be on holiday this weekend and probably won't look until next week. I'll let you know if I get started on it. 😄

**Comment by dustinsgoodman** [comment]
@adriencaccia PR is up for your review. It was a super simple change considering the conventions you follow on this repo. Enjoy and thanks for your work on this plugin!
